version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    image: ninjagor/api-gateway:latest
    platform: linux/amd64

  billing:
    build:
      context: .
      dockerfile: apps/billing/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    image: ninjagor/billing:latest
    platform: linux/amd64

  notifications:
    build:
      context: .
      dockerfile: apps/notifications/Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - .env
    image: ninjagor/notifications:latest
    platform: linux/amd64