version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env

  billing:
    build:
      context: .
      dockerfile: apps/billing/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
